---
galaxy_info:
  namespace: vbotka
  role_name: apache
  author: Vladimir Botka
  description: Install and configure Apache.
  company: https://botka.info
  github_branch: master
  license: BSD
  min_ansible_version: "2.20"
  platforms:
    - name: FreeBSD
      versions:
        - 13.5
        - 14.3
        - 15.0
  galaxy_tags:
    - freebsd
    - apache
dependencies:
  - jtyr.config_encoder_filters
collections:
  - community.general
