---
- name: "Files-markers: Debug markers in cl_files.values() cl_debug={{ cl_debug }}"
  when: cl_debug | bool
  ansible.builtin.debug:
    msg: "{{ cl_files.values() | selectattr('markers', 'defined') | list }}"

- name: "Files-markers: Mark blocks."
  ansible.builtin.include_tasks: fn/mark-block.yml
  loop: "{{ cl_files.values() | list | subelements('markers', skip_missing=true) }}"
  loop_control:
    label: "{{ item.0.path }}"

# EOF
