---
galaxy_info:
  namespace: vbotka
  role_name: freebsd_zfs
  author: Vladimir Botka
  description: FreeBSD. Configure ZFS.
  company: https://botka.info
  github_branch: master
  license: BSD
  min_ansible_version: "2.19"
  platforms:
    - name: FreeBSD
      versions:
        - 13.5
        - 14.2
        - 14.3
  galaxy_tags:
    - freebsd
    - zfs
dependencies: []
collections:
  - community.general
