apache_install: false
apache_confd: false
apache_servername: branch-server.example.com
apache_serveradmin: admin@branch-server.example.com

apache_ssl: true
apache_sslengine: 'on'
apache_sslcertificatekeyfile: "/usr/local/etc/ssl/private/{{ apache_servername }}.key"
apache_sslcertificatefile: "/usr/local/etc/ssl/certs/{{ apache_servername }}.crt"

apache_httpd_conf_modules:
  - {module: socache_shmcb_module, mod: mod_socache_shmcb.so}
  - {module: ssl_module, mod: mod_ssl.so}

apache_vhosts: true
apache_vhost:
  - ServerName: pull.example.com
    DocumentRoot: /usr/local/www/apache24/pull/
    SSLCertificateFile: "/usr/local/etc/ssl/certs/pull.example.com.crt"
    SSLCertificateKeyFile: "/usr/local/etc/ssl/private/pull.example.com.key"
    redirect: false

apache_directory_blocks:
  - Directory: /usr/local/www/apache24/data/
    Includefile: usr-local-www-apache-data.conf
    Conf:
      - "DirectoryIndex index.html index.htm"
      - "Options Indexes FollowSymLinks"
      - "AllowOverride All"
      - "Require all granted"
  - Directory: /usr/local/www/apache24/pull/
    Includefile: usr-local-www-apache-pull.conf
    Conf:
      - "DirectoryIndex index.html index.htm"
      - "Options Indexes FollowSymLinks"
      - "AllowOverride All"
      - "Require all granted"
