cl_dird_group: admin
cl_dird_dmode: "0770"
cl_dird: "{{ playbook_dir }}/conf-light"

cl_dira_group: admin
cl_dira_dmode: "0770"
cl_dira_fmode: "0660"

cl_handlers_dir_group: admin

install_delay: "{{ freebsd_install_delay }}"
install_retries: "{{ freebsd_install_retries }}"
