---
- name: Debug
  vars:
    msg: |-
      rsnapshot_role_version: {{ rsnapshot_role_version }}
      ansible_role_name: {{ ansible_role_name }}
      ansible_facts.architecture: {{ ansible_facts.architecture }}
      ansible_facts.os_family: {{ ansible_facts.os_family }}
      ansible_facts.distribution: {{ ansible_facts.distribution }}
      ansible_facts.distribution_major_version: {{ ansible_facts.distribution_major_version }}
      ansible_facts.distribution_version: {{ ansible_facts.distribution_version }}
      ansible_facts.distribution_release: {{ ansible_facts.distribution_release }}
      ansible_facts.python_version: {{ ansible_facts.python_version }}

      freebsd_install_method: {{ freebsd_install_method }}
      freebsd_use_packages: {{ freebsd_use_packages }}
      freebsd_cached: {{ freebsd_cached }}
      freebsd_state: {{ freebsd_state }}
      freebsd_use_globs: {{ freebsd_use_globs }}
      freebsd_install_retries: {{ freebsd_install_retries }}
      freebsd_install_delay: {{ freebsd_install_delay }}
      linux_install_retries: {{ linux_install_retries }}
      linux_install_delay: {{ linux_install_delay }}

      rsnapshot_install: {{ rsnapshot_install }}
      rsnapshot_packages:
        {{ rsnapshot_packages | to_nice_yaml(indent=2) | indent(2) }}
      rsnapshot_supported_linux_family: {{ rsnapshot_supported_linux_family }}
      rsnapshot_backup_conf: {{ rsnapshot_backup_conf }}
      rsnapshot_config_template: {{ rsnapshot_config_template }}
      rsnapshot_config_version: {{ rsnapshot_config_version }}
      rsnapshot_test: {{ rsnapshot_test }}
      rsnapshot_config_template_test: {{ rsnapshot_config_template_test }}

  ansible.builtin.debug:
    msg: "{{ '{}'.format(msg) }}"

# EOF
