---
- name: "Files-inifile: Debug ini in cl_files.values() cl_debug={{ cl_debug }}"
  when: cl_debug | bool
  ansible.builtin.debug:
    msg: "{{ cl_files.values() | selectattr('ini', 'defined') | list }}"

- name: "Files-inifile: INI files."
  register: cl_results_ini
  notify: "{{ item.0.handlers | d(omit) }}"
  community.general.ini_file:
    path: "{{ item.0.path }}"
    section: "{{ item.1.section }}"
    option: "{{ item.1.option | d(omit) }}"
    value: "{{ item.1.value | d(omit) }}"
    state: "{{ item.1.state | d(omit) }}"
    allow_no_value: "{{ item.1.allow_no_value | d(omit) }}"
    no_extra_spaces: "{{ item.1.no_extra_spaces | d(omit) }}"
    owner: "{{ item.0.owner | d(omit) }}"
    group: "{{ item.0.group | d(omit) }}"
    mode: "{{ item.0.mode | d(omit) }}"
    attributes: "{{ item.0.attributes | d(omit) }}"
    create: "{{ item.0.create | d(omit) }}"
    # backup: "{{ cl_backup }}"
  loop: "{{ cl_files.values() | list | subelements('ini', {'skip_missing': True}) }}"
  loop_control:
    label: "{{ item.0.path }} {{ item.1.section }} {{ item.1.option | d('UNDEFINED') }}"

- name: Debug
  when: cl_debug | bool
  block:

    - name: "Files-inifile: Debug cl_results_ini cl_debug={{ cl_debug }}"
      ansible.builtin.debug:
        var: cl_results_ini

    - name: "Files-inifile: Debug changed ini paths cl_debug={{ cl_debug }}"
      ansible.builtin.debug:
        msg: "{{ cl_results_ini.results | d([]) | json_query('[?changed].invocation.module_args.path') }}"

# EOF
