---
galaxy_info:
  namespace: vbotka
  role_name: rsnapshot
  author: Vladimir Botka
  description: Install and configure rsnapshot.
  company: https://botka.info
  github_branch: master
  license: BSD
  min_ansible_version: "2.20"
  platforms:
    - name: FreeBSD
      versions:
        - 13.5
        - 14.3
        - 15.0
    - name: Ubuntu
      versions:
        - jammy
        - noble
        - plucky
  galaxy_tags:
    - freebsd
    - linux
    - rsnapshot
dependencies: []
collections:
  - community.general
