---
# defaults for freebsd_iocage
freebsd_iocage_role_version: 1.2.0

freebsd_iocage_debug: false
freebsd_iocage_debug2: false

# Install packages
freebsd_iocage_install: true

# Enable iocage service
freebsd_iocage_enable: true
freebsd_iocage_start: false
freebsd_iocage_restart: false
freebsd_iocage_stop: false

# Backup configuration files
freebsd_iocage_backup_conf: false

# Quiet asserts
freebsd_iocage_assert_quiet: true

# Environment
freebsd_iocage_lang: "en_US.UTF-8"
freebsd_iocage_env:
  CRYPTOGRAPHY_OPENSSL_NO_LEGACY: '1'

# ZFS pool to activate iocage in
freebsd_iocage_pool: zroot
# ZFS pool mountpont:
freebsd_iocage_pool_mount: /mnt/zroot
# ZFS iocage mountpoint
freebsd_iocage_mount: "{{ freebsd_iocage_pool_mount }}/iocage"

# EOF
