- name: Stop and destroy jails.
  hosts: iocage

  vars:

    debug: false

  tasks:

    - name: Display vars.  # noqa: run-once
      when: debug | bool
      vars:
        project_jails_present: "{{ project | intersect(groups.all) }}"
      run_once: true
      ansible.builtin.debug:
        msg: |
          vmm:
            {{ vmm | to_yaml | indent(2) }}
          class:
            {{ class | to_yaml | indent(2) }}
          groups.all: {{ groups.all }}
          project_jails_present: {{ project_jails_present }}

    - name: Stop and destroy project jails.
      vars:
        iocage_jails_present: "{{ vmm[inventory_hostname] | intersect(groups.all) }}"
        uuids: "{{ iocage_jails_present | map('extract', hostvars, ['iocage_properties', 'host_hostuuid']) }}"
      block:

        - name: All jails already destroyed. End host.
          when: iocage_jails_present | length == 0
          ansible.builtin.meta: end_host

        - name: Stop jails.  # noqa: no-changed-when
          ansible.builtin.command: >
            iocage stop
            {{ uuids | join(' ') }}

        - name: Destroy jails.  # noqa: no-changed-when
          ansible.builtin.command: >
            iocage destroy
            --force
            {{ uuids | join(' ') }}
